dependencies:
  - PWNFinance/MultiToken@1.0.3
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@pwnfinance=PWNFinance/MultiToken@1.0.3'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  default: development
wallets:
  from_key: ${PRIVATE_KEY}